### ISSUE TITLE
Aritfact evaluation: Console Message in arith.rkt

### ISSUE THREAD

**Issue by rachitnigam** [brownplt/judgmental-resugaring#1]
Upon running `arith.rkt`, I get the following message.

   ```
   Ran 1 check.
   0 checks passed.
   Actual value differs from the expected value.
   Actual value: (derivation '(Γ ⊢ (not ~a) : Bool) "not" (list (derivation '(Γ ⊢ ~a : Bool) "premise" '())))
   Expected value: (derivation '(Γ ⊢ (not ~a) : Bool) "not" (list (derivation '(Γ ⊢ ~a : Bool) "assume" '())))

   In /home/rachit/Downloads/sweet/judgmental-resugaring-1.0/examples/arith.rkt at line 102 column 2
   ```
Is this expected? Should this be mentioned in the instructions? I also get the pop-up box with all the definitions.

**Comment by justinpombrio** [comment]
Oops, I renamed "assume" to "premise" a while back, but forgot to update
this test. Thanks.

**Comment by justinpombrio** [comment]
Fixed this a while back:
https://github.com/brownplt/judgmental-resugaring/commit/a21bb149619385d2967bf5b42c1c8603fad8b082
